/**
 * AI Flow 配置文件
 * 
 * @version 2.5.0
 * @description AI Flow 工作流配置，控制各 Stage 的行为
 * @updated 2026-03-20
 */

module.exports = {
platform: 'codeflicker',
mode: 'standard',
execution: {  mode: 'auto',
  reviewStages: [],
  blockBehavior: 'halt',
  forbiddenPhrases: ['准备进入', '现在可以开始', '接下来执行', '下一步是', '是否继续', '请确认是否'],
},
stages: {  preflight: {    enabled: true,
    skip_on_error: false,
  },
  requirementGate: {    enabled: true,
    strictness: 'standard',
    block_on_p0_gaps: true,
  },
  figma: {    enabled: true,
    auto_detect: true,
    require_for_ui_tasks: false,
  },
  planning: {    enabled: true,
    complexity_threshold: 60,
    force_on_keywords: ['复杂任务', '创建规划文件', '持久化规划'],
  },
  docsRecursiveRead: {    enabled: true,
    max_depth: 1,
  },
  techSolution: {    enabled: true,
    auto_generate_plan: true,
    require_yaml: true,
  },
  impactAnalysis: {    enabled: false,
    auto_enable_in_strict: true,
  },
  planFromTech: {    enabled: true,
    tdd_required: true,
  },
  verify: {    enabled: true,
    skip_in_lite: true,
  },
  iterate: {    enabled: true,
    test_first: true,
  },
},
guardian: {  enabled: true,
  stages: ['stage-1-guardian', 'stage-1.5-guardian', 'stage-1-6-guardian', 'stage-6-guardian'],
},
performance: {  timeouts: {    stage1: 30000,
    stage1_5: 45000,
    stage1_6: 60000,
    stage3: 120000,
    stage5: 90000,
    stage6: 60000,
    stage7: 300000,
  },
},
output: {  execution_trace: {    enabled: true,
    verbose: true,
    include_timestamps: true,
  },
  verification_report: {    enabled: true,
    include_suggestions: true,
  },
},
experimental: {  auto_gap_resolution: true,
  parallel_execution: false,
},
};
