import scrapy
from itemloaders.processors import TakeFirst, MapCompose
from w3lib.html import remove_tags

class NewsItem(scrapy.Item):
    url = scrapy.Field(output_processor=TakeFirst())
    title = scrapy.Field(output_processor=TakeFirst())
    content = scrapy.Field(
        input_processor=MapCompose(remove_tags),
        output_processor=TakeFirst()
    )
    published_at = scrapy.Field(output_processor=TakeFirst())
    author = scrapy.Field(output_processor=TakeFirst())
    site_domain = scrapy.Field(output_processor=TakeFirst())
    
    # Generated by AI
    country = scrapy.Field(output_processor=TakeFirst())
    news_type = scrapy.Field(output_processor=TakeFirst())
    language = scrapy.Field(output_processor=TakeFirst())
    
    # Aggregation ID
    event_id = scrapy.Field(output_processor=TakeFirst())
